### ISSUE TITLE
Is this being worked on?

### ISSUE THREAD

**Issue by zwoop** [aarons22/homebridge-bond#18]
I tried using this plugin with my Bond device, but even though it's identifying the accessory etc., it's not working at all. I'm guessing (but certainly not sure) that it's because my ceiling fan remote does not have variable speed, but 0-1-2-3. I guess I would have expected this to map to 0% - 33% - 67% - 100%, but a) it does not work at all (no percentages work) and b) I can only set it to 33% and 100% (at 67% it changes to either 33% or 100%).

So, I'm mostly curious if this is a project people are still working on?

**Comment by cargueta001** [comment]
@zwoop It appears that the original developer of this plugin is no longer working on this. It's dated as of 5 months ago since the last update. A few people have somehow gotten this to work but I have posted in a previous thread that the new Bond API perhaps broke the plugin rendering it useless to several of us. It was working for me prior and am disappointed that we are unable to use it. I have, however, looked up a method using IFTTT as a link to have my Bond fans appear in the Home app with great success. I found this method originally in a Reddit post and found it to be pretty straight forward once you get the basics out of the way. I'd recommend going that route if you're interested.

**Comment by jimboslicethat** [comment]
Yes, I am having the same issue @zwoop. The accessories make it to homekit, but they dont actually do anything.

It appears that bond is moving to their V2 API, which they are calling [Local API](https://forum.bondhome.io/t/bond-local-api-beta-sign-up/250), and it is currently in beta. Which means that if you wanted to rip out the current code that does the existing API call to bond, youd need to get a beta key first.

@cargueta001 would you mind dropping a link to the IFTT integration? I am super interested in going that route and learning more about your current setup.

**Comment by cargueta001** [comment]
@jimboslicethat Apologies for the late response. But I do want to show you how I was able to successfully implement the Bond accessories.

I followed [this thread](https://www.reddit.com/r/homebridge/comments/868wiy/bond_plugin_for_homebridge/?depth=1) to create the basis of controlling the Bond through [IFTTT](https://ifttt.com/bond) which is then connected via a [Homebridge plugin](https://github.com/ilcato/homebridge-ifttt). You'll need to create the formula as needed and program this using a IFTTT account. Once you've done that, your formulas will need to be added to your config file in Homebridge.

It's a bit of a setup, but once you get the hang of it, you'll have your parameters and options available in the Home app.

![IMG_A7B1C77672D8-1](https://user-images.githubusercontent.com/48275759/57032417-2ac69280-6bff-11e9-8ec0-2419b4ac16c2.jpeg)

**Comment by vdotn** [comment]
Yes, this plugin still works with Bond. I use it daily. 

What you’re seeing is the behavior when an api call fails. I had the same problem and debugged it to be a dns issue, where a .local is hardcored in the URL. I patched it on my machine some time ago but yesterday submitted a pull request which I believe will address the issue.

You should be able to see in your logs if an api call fails and throws an error, and go from there.

**Comment by jimboslicethat** [comment]
@vdotn it depends on what version of firmware you are on. You're Bond is probably on the older firmware version which explains why the plugin is still working (The older firmware version is tied to the API that this plugin was originally written for).

**Comment by vdotn** [comment]
Was there a new hardware rev tied with new firmware? Mine is showing FW 1.138.1 and when I do check for updates it says no new updates available.

**Comment by plapke** [comment]
So my firmware version is 1.138.3 (1), does that mean this will no longer work for me?  I am just now trying to get it set up.  I can see the fan/light in my home app and in the app it says that the light comes "on" but nothing actually happens.  And when I try to turn the fan on it won't go above 0%.  And the reset fan won't switch off of "off".  Is there anything I do to make it work?

**Comment by vdotn** [comment]
That bounce-back behavior on the fan happens when the command fails to run. Check your log for anything useful. This works with the 1.x firmware train.

**Comment by plapke** [comment]
So honestly I'm not sure what I'm looking for in the log.  

Attached is a copy of them, any chance you can take a look to see if you see anything?

[bond log.pdf](https://github.com/edc1591/homebridge-bond/files/3293766/bond.log.pdf)

**Comment by vdotn** [comment]
You’re getting dns time-out. Can you test my PR? I saw your exact issue and believe I fixed it here: https://github.com/edc1591/homebridge-bond/pull/19

Out of curiosity, are you using Eero routers?

**Comment by plapke** [comment]
I tried your PR, and forgive me I'm new to this, initially I uninstalled the original plugin, but then it gave me an error that "Error: The requested platform 'Bond' was not registered by any plugin." 

I'm guessing that wasn't supposed to happen and I did something wrong

**Comment by plapke** [comment]
I looked at the files you modified (bond.js, bond.ts, index.ts, index.js), and tried to make those changes in the files in the homebridge-bond files that were originally from the plugin, but that didn't seem to change anything...again, very new at this so sorry if i'm doing something wrong that should be obvious

**Comment by vdotn** [comment]
Ok no worries. Reason I asked if you use Eero is because they don’t support local dns and I had to do some crazy sh*t to get it to work on mine.

Well turns out, Orbi seems to be the same! See this thread: https://community.netgear.com/t5/Idea-Exchange-For-Home/orbi-add-dns-server/idc-p/1632085

I bet you can work around this by creating a static entry in your OS’s hosts file. If you don’t know how to do that I’ll try to help you but need some details about your setup:  (server/OS, Docker/VM/Native, etc.) and also need to figure out the internal IP address of your BOND.

**Comment by zwoop** [comment]
I tried again, but still not working (at all). I'm getting errors such

```
[6/24/2019, 4:04:40 PM] [Bond] { StatusCodeError: 404 - "{}\r\n"
    at new StatusCodeError (/usr/local/lib/node_modules/homebridge-bond/node_modules/request-promise/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/usr/local/lib/node_modules/homebridge-bond/node_modules/request-promise/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/homebridge-bond/node_modules/request-promise/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-bond/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-bond/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-bond/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'StatusCodeError',
  statusCode: 404,
  message: '404 - "{}\\r\\n"',
  error: '{}\r\n',
```

Are we sure this plugin is supposed to work with the latest firmware in the Bond hubs? From what I can tell, they moved on to a "v2" of their APIs, which seems completely different.

**Comment by jimboslicethat** [comment]
@zwoop I think that's the crux of the issue. I tried hitting the APIs that this package is setup to hit, and those aren't even available. A simple test in postman shows that these APIs need to be reworked in order to be compatible with the v2 version. It feels like we need to fork this repo, or get @edc1591 to transfer ownership to someone so that we can start making progress toward making this plugin actually useful.

**Comment by evandcoleman** [comment]
I no longer use a Bond device, so I likely won't be maintaining this plugin in the future. Having said that, I'd be happy to talk to anyone who'd like to take ownership of this repo.

**Comment by iRayanKhan** [comment]
I wouldn’t mind. If not me, Plainsane or vdotn are the other 2 best candidates.

**Comment by jimboslicethat** [comment]
Let's do what we need to do to get ownership transferred to the best candidates! Good to hear we aren't going to let this project die. It would be great to get some of these PR's merged in so we can get things working again.

**Comment by aarons22** [comment]
Hey all! I created a new plugin using the v2 API, which can be found here: https://github.com/aarons22/homebridge-bond-v2

Since the API was dramatically different, it didn't make a ton of sense to fork the repo, but I did use a lot of what @evandcoleman wrote previously for inspiration.

**Comment by jimboslicethat** [comment]
FWIW I highly recommend everybody move to @aarons22's package. It's running great and he's pushed several updates just in the last few days. Thank you for your work! 👍

**Comment by zwoop** [comment]
I just installed this new plugin as well, and it works great! Thanks!

I think we should leave this issue open for others to find this information.

**Comment by evandcoleman** [comment]
Seems like it might make sense to transfer this repo over to @aarons22 so he can use the plugin name with the `v2` suffix. Does that sound good to everyone?

**Comment by iRayanKhan** [comment]
I think thats a great idea, thanks for the plugin!

**Comment by aarons22** [comment]
I’m good with that! Can you transfer the npm package to me as well?

**Comment by evandcoleman** [comment]
Yup! What's your npm username?

**Comment by aarons22** [comment]
same as my github: `aarons22`

Thanks!

**Comment by evandcoleman** [comment]
Done!

**Comment by evandcoleman** [comment]
I'd recommend removing me as a maintainer from npm once you've confirmed you have access. No need to risk having more people with access.

**Comment by aarons22** [comment]
Awesome, thanks again @evandcoleman for your work on this plugin!

To everyone else, I'll transition my other plugin code to this repo in the next day or so and deprecate the other plugin.

**Comment by vdotn** [comment]
Might I recommend leaving a fork of v1 still available? It seems not everyone is able to upgrade to 2.0. Interestingly enough I’m not, and my device isn’t even a year old. Kind of a dick move from the bond folks but it is what it is. 

https://olibra.zendesk.com/hc/en-us/articles/360007186371-bond-bridge-Current-Application-Version-

**Comment by jimboslicethat** [comment]
If you download the new Bond Home app you should be able to get the new
firmware update.

**Comment by vdotn** [comment]
I followed that but it’s actually not true for all modes. Check the link I posted, some s/n ranges are capped at 1.x

**Comment by aarons22** [comment]
While it’s true that you should be able to get new firmware with the new Bond Home app (I have this noted in the other repo right now), I’ll add some instructions for those who want to stay on v1 firmware. You’ll be able to reference a specific npm package version. 

If someone wants to maintain v1 support, they should fork it and create a new package!

**Comment by aarons22** [comment]
@vdotn interesting, and super annoying 🙄

I can throw up a v1 repo/package but I’m not going to maintain it at all. I feel like we’d be better off just referencing the version number of this repo for users of the v1 api. Thoughts?

**Comment by vdotn** [comment]
@aarons22 good with me, it’s fairly feature complete anyway. May throw one or two PRs if I have time but that’s about it, it works well.

**Comment by aarons22** [comment]
v2 code has been migrated and a new version (2.0.0) has been published 🚀 

I created another package for v1 users called `homebridge-bond-v1` and published 1.0.0. I won't be maintaining it, but if someone comes along and wants to do anything with it I'll be happy to pass it along.

I'll be deprecating the v2 plugin and pulling it from npm in the coming weeks.
